# Generated by Django 3.2.3 on 2021-05-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userflow', '0002_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
    ]
